nelmio_api_doc:
    documentation:
        info:
            title: My App
            description: This is an awesome app!
            version: 1.0.0
    areas: # to filter documented areas
        feed:
            path_patterns:
                - ^/api/v1/get-feed
        default:
            path_patterns:
                - ^/api(?!/doc(.json)?$)
